### PR TITLE
Implementation of the Catalog of  my Things console App

### PR DESCRIPTION
**Pull request by bienvenuushindi**
# Project Description
In this project, we worked in a team of 3 members. Each one was assigned specific tasks 
[This video](https://drive.google.com/file/d/1I0ZTVuMGFdTeiWukzdqy-lK-cY4U-3ER/view?usp=sharing) presents the project
## Tasks List
- [x] #1 
- [x] #2 
- [x] #3 
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #7 
- [x] #8
- [x] #9 
- [x] #10
- [x] #11 
- [x] #12
- [x] #14 
- [x] #15
- [x] #16
- [x] #17 
- [x] #18 
- [x] #19 
- [x] #20 
- [x] #21
- [x]  #22
- [x]  #23 
- [x] #24
- [x]  #25
- [x]  #26
- [x]  #27
- [x]  #28
- [x]  #29
- [x]  #30
- [x]  #31 
- [x] #32 
- [x] #33

### CODE REVIEW

**Review by VICTOR-CHUKWU — APPROVED** [review]
Hi Team,
# STATUS: APPROVED! 🥇 💯 
- [x] This is actually one of the best project I have reviewed. Bravo!!!  :clap: 
done

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by bienvenuushindi** [comment]
@VICTOR-CHUKWU Thank you very much for reviewing our work and your appreciation

**Comment by ChrispaixK** [comment]
Thanks a lot @VICTOR-CHUKWU

**Comment by pinkmoon25** [comment]
Thank you @VICTOR-CHUKWU for the review and thanks for the appreciation it means alot 🙏

**Pull request merged**
